# Generated by Django 5.1.3 on 2024-11-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='affiliate_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
