# Generated by Django 5.1.3 on 2024-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_productpage_affiliate_link_productpage_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='free_return',
            field=models.BooleanField(default=False, verbose_name='Free Return'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (currency)'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='saving_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saving Amount (currency)'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='specail_intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
